// Generated with ./gendistros.py

package pkgcloud

var debDistroIDs = map[string]int{
	"ubuntu/warty":      1,
	"ubuntu/hoary":      2,
	"ubuntu/breezy":     3,
	"ubuntu/dapper":     4,
	"ubuntu/edgy":       5,
	"ubuntu/feisty":     6,
	"ubuntu/gutsy":      7,
	"ubuntu/hardy":      8,
	"ubuntu/intrepid":   9,
	"ubuntu/jaunty":     10,
	"ubuntu/karmic":     11,
	"ubuntu/lucid":      12,
	"ubuntu/maverick":   13,
	"ubuntu/natty":      14,
	"ubuntu/oneiric":    15,
	"ubuntu/precise":    16,
	"ubuntu/quantal":    17,
	"ubuntu/raring":     18,
	"ubuntu/saucy":      19,
	"ubuntu/trusty":     20,
	"ubuntu/utopic":     142,
	"ubuntu/vivid":      148,
	"ubuntu/wily":       152,
	"debian/etch":       21,
	"debian/lenny":      22,
	"debian/squeeze":    23,
	"debian/wheezy":     24,
	"debian/jessie":     25,
	"debian/stretch":    149,
	"debian/buster":     150,
	"any/any":           35,
	"linuxmint/petra":   157,
	"linuxmint/qiana":   158,
	"linuxmint/rebecca": 159,
	"linuxmint/rafaela": 160,
	"linuxmint/rosa":    161,
	"raspbian/wheezy":   153,
	"raspbian/jessie":   154,
	"raspbian/stretch":  155,
	"raspbian/buster":   156,
}
